### ISSUE TITLE
Hello, I'm getting the following error while trying to run model test, with part of NTU RGB+D dataset:

### ISSUE THREAD

**Issue by dongle329** [kenziyuliu/DGNN-PyTorch#23]

**Comment by dongle329** [comment]
Model total number of params: 4089320
[ Sat Jun 20 08:05:09 2020 ] Load weights from ./runs/ntu_cs_dgnn_spatial-49-62600.pt.
[ Sat Jun 20 08:05:09 2020 ] Model:   model.dgnn.Model.
[ Sat Jun 20 08:05:09 2020 ] Weights: ./runs/ntu_cs_dgnn_spatial-49-62600.pt.
[ Sat Jun 20 08:05:09 2020 ] Eval epoch: 1
  0%|                                                                                                                     | 0/516 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 606, in <module>
    processor.start()
  File "main.py", line 567, in start
    self.eval(epoch=0, save_score=self.arg.save_score, loader_name=['test'], wrong_file=wf, result_file=rf)
  File "main.py", line 491, in eval
    output = self.model(joint_data, bone_data)
  File "/home/min1/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/min1/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/min1/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/min1/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/min1/anaconda3/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/min1/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/min1/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/min1/cf3d08d5-3d6b-457d-bef5-1b12560aef78/DL/Unofficial-DGNN-PyTorch-master/model/dgnn.py", line 184, in forward
    fv, fe = self.l2(fv, fe)
  File "/home/min1/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/min1/cf3d08d5-3d6b-457d-bef5-1b12560aef78/DL/Unofficial-DGNN-PyTorch-master/model/dgnn.py", line 123, in forward
    fv, fe = self.dgn(fv, fe)
  File "/home/min1/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/min1/cf3d08d5-3d6b-457d-bef5-1b12560aef78/DL/Unofficial-DGNN-PyTorch-master/model/dgnn.py", line 85, in forward
    fv = fv.view(N, -1, V_node)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

**Comment by dongle329** [comment]
my torch=1.3.1

**Comment by GedamuA** [comment]
use reshape instead of view 

# Reshape for matmul, shape: (N, CT, V)
        fv = fv.reshape(N, -1, V_node)
        fe = fe.reshape(N, -1, V_edge)

**Comment by GedamuA** [comment]
fv = fv.reshape(N, -1, V_node)

**Comment by jvitorcardoso** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
quektc, @jiezi19971225, @Wangzhijie2016, @ahoskins, @D111GENT, @yahoho106, @39km, @mimounraddahi, @Harrisonp365, @shaowenliu, @ilwwmmh, @Atharva6555, @jurisliepins, @caicaicaich, @ayazurrehman, @Icosa2050, @yuyear, @kencodible, @svpplynd3mand, @qimiaojiyi

**Comment by kencodible** [comment]
Hello GitHub Recruitment Team,

Last night I accepted a better offer at the startup I’m currently working at and am no longer interested in this position. Thank you for selecting me for this process! I will keep you in mind for the future. I still LOOOVE GitHub and would like to work there one day.

Cheers,

Kent Bull
Authentic Data Architect | Encodible
***@***.***
